### ISSUE TITLE
xiaomi.eu cannot pass device integrity test

### ISSUE THREAD

**Issue by zhouhm** [chiteroman/PlayIntegrityFix#129]
I have installed KernelSU v0.7.1 Zygisk-Next-v4-0.8.1-111-release.zip Shamiko-v0.7.4-188-release.zip PlayIntegrityFix_v14.1.zip， and I rm -f /data/adb/modules/playintegrityfix/pif.json.
and add the following file
```
# /data/adb/ksu/bin/busybox vi /data/adb/pif.json
{
  "PRODUCT": "WW_Phone",
  "DEVICE": "ASUS_Z012D",
  "MANUFACTURER": "asus",
  "BRAND": "asus",
  "MODEL": "ASUS_Z012D",
  "FINGERPRINT": "asus/WW_Phone/ASUS_Z012D:7.0/NRD90M/14.2015.1701.8-20170222:user/release-keys",
  "SECURITY_PATCH": "2017-01-01",
  "FIRST_API_LEVEL": "23"
}
```
and I have cleared Play service and Play Store data, finally reboot my phone.

**Comment by williamgateszhao** [comment]
With xiaomi.eu rom, you can use pif 14.0 WITHOUT custom pif.json, so pif just let you pass safetynet, xiaomi.eu will cover everything else. If you don't use pif (or universal safetynet fix) to pass the safetynet, xiaomi.eu will not get the BASIC INTEGRITY while your phone is rooted.

**Comment by smrky1** [comment]
> ... and add the following file

Can you please remove the file quotation? We do not want it to get banned by Google... Thanks

**Comment by crok** [comment]
It's already been banned like 2 hours ago.

**Comment by williamgateszhao** [comment]
> It's already been banned like 2 hours ago.

Yes...So you can update the apk from xiaomi.eu, or completely uninstall the inject module of xiaomi.eu and use pif 14.1 with custom pif.json. Works for me.
Completely uninstall eu.xiaomi.module.inject needs root permission, just uninstall the update of the app does not help.
BE CAREFUL: By uninstall it, you may not be able reinstall update apk of the inject module from xiaomi.eu

**Comment by craxton** [comment]
I use xiaomi eu rooted with etc. 14.0.10 ATM, with this spoofing module, and always have checked Google Play services. (All options) empower, Netflix, (Mario run) all work with these options ticked. Unsure if I need to keep updating the module, as play services was unticked last I checked and re ticked. Come to think of it, dam near ANYTHING that has "Google" in os app, that pops up when I search it in deny options I tick that shxx. Only reason I found myself here was due to not re ticking the options, but I still keep this, as it's easier and passes two options on integrity checking vs just "basic" as before. Gonna donate for dudes hardwork at this, as his lines in the module are SPOT ON with what I'm feeling towards Googles bullspit ATM.
