### ISSUE TITLE
14.6 not getting strong Integrity

### ISSUE THREAD

**Issue by hoper21** [chiteroman/PlayIntegrityFix#183]
Hello. as shown as a title, i cant get 3 pass green for integrity check especially strong integrity. 

My model device & OS:
Infinix S4 X626B LTE
Android 9.0 (API 28)

Apps Safetynet Checker:
TB Checker

Rooting apps:
Magisk v26.4 (26400)

Module On:
Shamiko v0.7.5 (with Enforce Denylist Off)

Screenshot from TB Checker:
![Screenshot_20231222-160216](https://github.com/chiteroman/PlayIntegrityFix/assets/63699291/698d8c92-853d-4f32-8896-a75026a411dc)

**Comment by furdiburd** [comment]
Strong integrity is impossible to pass. Close this

**Comment by SpeedyCraftah** [comment]
> Strong integrity is impossible to pass. Close this

Wouldn't say impossible but not possible at the moment, at least with what we know.

**Comment by leo60228** [comment]
If an exploit is found to pass STRONG attestation on a given device when not running stock software, that exploit will either be fixed server-side if possible (like what happened with the Pixel 7 series a few months ago), or the affected devices will be blocked from STRONG attestation entirely. There's a reason Google warns developers against requiring STRONG attestation.

**Comment by chiteroman** [comment]
There are several ways to pass the Strong verdict, but obviously I'm not going to publish them. If I did, it wouldn't take Google a day to fix them.

**Comment by SpeedyCraftah** [comment]
> There are several ways to pass the Strong verdict, but obviously I'm not going to publish them. If I did, it wouldn't take Google a day to fix them.

That's interesting, of course there's no point in publishing them publicly since for Google the strong verdict is their magnum opus of verifying integrity so they are definitely constantly on the lookout for bypasses.

I'm not too involved in the android world but as far as I know the most direct way to pass strong integrity would be to either side channel attack the TEE and extract the signature so that verdicts can be spoofed, or exploit vulnerabilities in the TEE so that the unsafe and secure sides of the processor can be bridged and the verdict spoofed that way (there was a research paper published and there have already been many many vulnerabilities ranging from minor to critical discovered in these secure processors).
