### ISSUE TITLE
Not working on Lineageos 21 Mi 9 lite

### ISSUE THREAD

**Issue by Danik2343** [chiteroman/PlayIntegrityFix#419]
Not working on Lineageos 21
Device: Mi 9 Lite

**Comment by kaputtnix** [comment]
It is working on LineageOS 21...
But since the update to Android 14 (LineageOS 21) i have to download and
flash the "boot.img" with every update. 
Otherwise even magisk isn't working.
Device: Sony Xperia XZ2 compact

**Comment by tigockel** [comment]
This is not a general problem with Lineageos 21.
Title should be more specific.

**Comment by foundObjects** [comment]
Working fine on LOS21 here on my OnePlus 7T

**Comment by Danik2343** [comment]
When you reboot the phone, the Basic test passes, but then the tests fail, including Basic.

**Comment by tigockel** [comment]
Again, this is not a general LOS21 problem! I'm running the current update for OnePlus9Pro (lemonadep / le2123) without complications. If you need help you should make your problem more specific. First step could be, as I mentioned before, change the title to something more relevant by adding your device.

Also, maybe you could include your magisk-log, since it could give relevant information for what modules you have installed and what you have configured in your deny-list.

**Comment by Danik2343** [comment]
[Uploading magisk_log_2024-09-16T18.31.31.log…]()

**Comment by chiteroman** [comment]
No logs = no help
